server {
    listen 80;
    server_name kvm-app.technotim.live;

    # Serve the Vite app from the `dist` folder
    root /var/www
    index index.html;

    location / {
        try_files $uri /index.html =404;
    }
}
